allow-lan: true
dns:
  enable: true
  nameserver:
  - 114.114.114.114
  - 8.8.8.8
external-controller: 0.0.0.0:9090
log-level: info
mixed-port: 7890
mode: rule
proxies:
- name: ğŸ‡«ğŸ‡·[FR]æ³•å›½-Paris01
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11001
  server: fr1.t11-a.app
  sni: fr01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡«ğŸ‡·[FR]æ³•å›½-Paris02
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11002
  server: fr2.t11-a.app
  sni: fr02t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¬ğŸ‡§[UK]è‹±å›½Coventry01-BBCä¼˜åŒ–
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11003
  server: uk1.t11-a.app
  sni: uk01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¬ğŸ‡§[UK]è‹±å›½Coventry02-BBCä¼˜åŒ–
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11005
  server: uk2.t11-a.app
  sni: uk02t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡©ğŸ‡ª[DE]å¾·å›½-Frankfurt01
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11006
  server: de1.t11-a.app
  sni: de01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡©ğŸ‡ª[DE]å¾·å›½-Frankfurt02
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11007
  server: de2.t11-a.app
  sni: d2.t11-a2.click
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¨ğŸ‡¦[CA]åŠ æ‹¿å¤§-Toronto
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11008
  server: ca1.t11-a.app
  sni: ca01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡³ğŸ‡±[NL]è·å…°-Amsterdam
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11009
  server: nl1.t11-a.app
  sni: nl01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡·ğŸ‡º[RU]ä¿„ç½—æ–¯-Moscow
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11010
  server: ru1.t11-a.app
  sni: ru01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¹ğŸ‡·[TR]åœŸè€³å…¶-Istanbul
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11051
  server: tr1.t11-a.app
  sni: tr01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡®ğŸ‡³[IN]å°åº¦-bangalore
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11033
  server: in1.t11-a.app
  sni: in01tt.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡°ğŸ‡·[KR]éŸ©å›½-Seoul
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11029
  server: kr1.t11-a.app
  sni: kr011t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡»ğŸ‡³[VN]è¶Šå—-HoChiMinh
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11015
  server: vn1.t11-a.app
  sni: vn01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¦ğŸ‡º[AU]æ¾³å¤§åˆ©äºš-Sydney
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11016
  server: au1.t11-a.app
  sni: au01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡³ğŸ‡¬[NG]å°¼æ—¥åˆ©äºš-Lagos
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11017
  server: ng1.t11-a.app
  sni: ng01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¦ğŸ‡·[AR]é˜¿æ ¹å»·-BuenosAires
  password: 4a2ed7af-d29a-4d89-a077-dfd2956afba0
  port: 11018
  server: ar1.t11-a.app
  sni: ar01t.goodyun.buzz
  tls: true
  type: trojan
  udp: true
- alterId: 0
  cipher: auto
  name: HK1
  network: tcp
  port: 39287
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: HK2
  network: tcp
  port: 28373
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: HK3
  network: tcp
  port: 11090
  server: cn02.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: JP1
  network: tcp
  port: 48445
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: JP2
  network: tcp
  port: 18693
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: JP3
  network: tcp
  port: 22367
  server: cn02.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: SG1
  network: tcp
  port: 37797
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: SG2
  network: tcp
  port: 36585
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: SG3
  network: tcp
  port: 50940
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: TW1
  network: tcp
  port: 18565
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: TW2
  network: tcp
  port: 18368
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: KR1
  network: tcp
  port: 25283
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: US1
  network: tcp
  port: 25507
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: US2
  network: tcp
  port: 35510
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: US3
  network: tcp
  port: 38733
  server: cn01.gene.7xn.cn
  tls: false
  type: vmess
  uuid: 82603e44-061f-4564-92d1-04dc3942afbb
  ws-opts: {}
- alterId: 0
  cipher: auto
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯_03
  network: ws
  port: 44552
  server: hk03.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- name: ğŸ‡­ğŸ‡°+é¦™æ¸¯-07
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 44302
  server: hk07.jsytongxin.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- alterId: 0
  cipher: auto
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯_09
  network: ws
  port: 51254
  server: hk18.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- name: ğŸ‡¯ğŸ‡µ+æ—¥æœ¬-13
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 30502
  server: jp13.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¯ğŸ‡µ+æ—¥æœ¬-14
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 39204
  server: jp14.jsyjiedian8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¯ğŸ‡µ+æ—¥æœ¬-15
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 39555
  server: jp15.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¸ğŸ‡¬+æ–°åŠ å¡-13
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 45177
  server: sg13.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¸ğŸ‡¬+æ–°åŠ å¡-14
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 45078
  server: sg14.jsyjiedian8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¸ğŸ‡¬+æ–°åŠ å¡-15
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 45179
  server: sg15.stimaysmhy8.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ ç¾å›½-08
  network: ws
  port: 40601
  server: us05.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ ç¾å›½-09
  network: ws
  port: 40706
  server: us09.stimaysmhy8.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- alterId: 0
  cipher: auto
  name: ğŸ‡ºğŸ‡¸ ç¾å›½-10
  network: ws
  port: 40707
  server: us10.jsyjiedian8.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- name: ğŸ‡°ğŸ‡·+éŸ©å›½-01
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 48705
  server: kr01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡°ğŸ‡·+éŸ©å›½-02
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 48702
  server: kr02.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡°ğŸ‡·+éŸ©å›½-03
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 48505
  server: kr03.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡®ğŸ‡³+å°åº¦-1
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 25538
  server: in01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡®ğŸ‡³+å°åº¦-2
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 44856
  server: in02.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡³ğŸ‡±+è·å…°
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 30012
  server: nl01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡µğŸ‡­+è²å¾‹å®¾
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 19190
  server: ph01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¦ğŸ‡·+é˜¿æ ¹å»·
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 45715
  server: ar01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡®ğŸ‡¹+æ„å¤§åˆ©
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 15004
  server: it01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¹ğŸ‡·+åœŸè€³å…¶
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 43719
  server: tr01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡»ğŸ‡³+è¶Šå—
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 40511
  server: vn01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¦ğŸ‡ª+è¿ªæ‹œ
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 40708
  server: ae01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡²ğŸ‡¾+é©¬æ¥è¥¿äºš
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 45720
  server: my01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡«ğŸ‡·+æ³•å›½
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 15713
  server: fr01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡¦ğŸ‡º+æ¾³å¤§åˆ©äºš
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 35303
  server: au01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡ªğŸ‡¸+è¥¿ç­ç‰™
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 40523
  server: es01.jsylianjie5.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡²ğŸ‡½+å¢¨è¥¿å“¥
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 35661
  server: mx01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- name: ğŸ‡·ğŸ‡º+ä¿„ç½—æ–¯
  password: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  port: 42721
  server: ru01.jsylianjie6.com
  sni: jsygouer.weixin-baidu-qq.com
  tls: true
  type: trojan
  udp: true
- alterId: 0
  cipher: auto
  name: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
  network: ws
  port: 40717
  server: ca01.jsylianjie5.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- alterId: 0
  cipher: auto
  name: ğŸ‡§ğŸ‡· å·´è¥¿
  network: ws
  port: 18132
  server: br01.jsylianjie5.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
- alterId: 0
  cipher: auto
  name: ğŸ‡¬ğŸ‡§ è‹±å›½
  network: ws
  port: 45712
  server: gb01.jsylianjie5.com
  tls: false
  type: vmess
  uuid: 7bcc439b-e4e3-4616-b923-07f83b08e09d
  ws-opts:
    path: ''
proxy-groups:
- name: Auto
  proxies:
  - ğŸ‡«ğŸ‡·[FR]æ³•å›½-Paris01
  - ğŸ‡«ğŸ‡·[FR]æ³•å›½-Paris02
  - ğŸ‡¬ğŸ‡§[UK]è‹±å›½Coventry01-BBCä¼˜åŒ–
  - ğŸ‡¬ğŸ‡§[UK]è‹±å›½Coventry02-BBCä¼˜åŒ–
  - ğŸ‡©ğŸ‡ª[DE]å¾·å›½-Frankfurt01
  - ğŸ‡©ğŸ‡ª[DE]å¾·å›½-Frankfurt02
  - ğŸ‡¨ğŸ‡¦[CA]åŠ æ‹¿å¤§-Toronto
  - ğŸ‡³ğŸ‡±[NL]è·å…°-Amsterdam
  - ğŸ‡·ğŸ‡º[RU]ä¿„ç½—æ–¯-Moscow
  - ğŸ‡¹ğŸ‡·[TR]åœŸè€³å…¶-Istanbul
  type: select
- interval: 300
  name: LoadBalance
  proxies:
  - ğŸ‡«ğŸ‡·[FR]æ³•å›½-Paris01
  - ğŸ‡«ğŸ‡·[FR]æ³•å›½-Paris02
  - ğŸ‡¬ğŸ‡§[UK]è‹±å›½Coventry01-BBCä¼˜åŒ–
  - ğŸ‡¬ğŸ‡§[UK]è‹±å›½Coventry02-BBCä¼˜åŒ–
  - ğŸ‡©ğŸ‡ª[DE]å¾·å›½-Frankfurt01
  - ğŸ‡©ğŸ‡ª[DE]å¾·å›½-Frankfurt02
  - ğŸ‡¨ğŸ‡¦[CA]åŠ æ‹¿å¤§-Toronto
  - ğŸ‡³ğŸ‡±[NL]è·å…°-Amsterdam
  - ğŸ‡·ğŸ‡º[RU]ä¿„ç½—æ–¯-Moscow
  - ğŸ‡¹ğŸ‡·[TR]åœŸè€³å…¶-Istanbul
  - ğŸ‡®ğŸ‡³[IN]å°åº¦-bangalore
  - ğŸ‡°ğŸ‡·[KR]éŸ©å›½-Seoul
  - ğŸ‡»ğŸ‡³[VN]è¶Šå—-HoChiMinh
  - ğŸ‡¦ğŸ‡º[AU]æ¾³å¤§åˆ©äºš-Sydney
  - ğŸ‡³ğŸ‡¬[NG]å°¼æ—¥åˆ©äºš-Lagos
  - ğŸ‡¦ğŸ‡·[AR]é˜¿æ ¹å»·-BuenosAires
  - HK1
  - HK2
  - HK3
  - JP1
  - JP2
  - JP3
  - SG1
  - SG2
  - SG3
  - TW1
  - TW2
  - KR1
  - US1
  - US2
  - US3
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_03
  - ğŸ‡­ğŸ‡°+é¦™æ¸¯-07
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_09
  - ğŸ‡¯ğŸ‡µ+æ—¥æœ¬-13
  - ğŸ‡¯ğŸ‡µ+æ—¥æœ¬-14
  - ğŸ‡¯ğŸ‡µ+æ—¥æœ¬-15
  - ğŸ‡¸ğŸ‡¬+æ–°åŠ å¡-13
  - ğŸ‡¸ğŸ‡¬+æ–°åŠ å¡-14
  - ğŸ‡¸ğŸ‡¬+æ–°åŠ å¡-15
  - ğŸ‡ºğŸ‡¸ ç¾å›½-08
  - ğŸ‡ºğŸ‡¸ ç¾å›½-09
  - ğŸ‡ºğŸ‡¸ ç¾å›½-10
  - ğŸ‡°ğŸ‡·+éŸ©å›½-01
  - ğŸ‡°ğŸ‡·+éŸ©å›½-02
  - ğŸ‡°ğŸ‡·+éŸ©å›½-03
  - ğŸ‡®ğŸ‡³+å°åº¦-1
  - ğŸ‡®ğŸ‡³+å°åº¦-2
  - ğŸ‡³ğŸ‡±+è·å…°
  - ğŸ‡µğŸ‡­+è²å¾‹å®¾
  - ğŸ‡¦ğŸ‡·+é˜¿æ ¹å»·
  - ğŸ‡®ğŸ‡¹+æ„å¤§åˆ©
  - ğŸ‡¹ğŸ‡·+åœŸè€³å…¶
  - ğŸ‡»ğŸ‡³+è¶Šå—
  - ğŸ‡¦ğŸ‡ª+è¿ªæ‹œ
  - ğŸ‡²ğŸ‡¾+é©¬æ¥è¥¿äºš
  - ğŸ‡«ğŸ‡·+æ³•å›½
  - ğŸ‡¦ğŸ‡º+æ¾³å¤§åˆ©äºš
  - ğŸ‡ªğŸ‡¸+è¥¿ç­ç‰™
  - ğŸ‡²ğŸ‡½+å¢¨è¥¿å“¥
  - ğŸ‡·ğŸ‡º+ä¿„ç½—æ–¯
  - ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
  - ğŸ‡§ğŸ‡· å·´è¥¿
  - ğŸ‡¬ğŸ‡§ è‹±å›½
  strategy: consistent-hashing
  type: load-balance
  url: http://www.gstatic.com/generate_204
rules:
- DOMAIN-SUFFIX,google.com,Auto
- DOMAIN-SUFFIX,youtube.com,Auto
- DOMAIN-KEYWORD,google,Auto
- MATCH,DIRECT
